### ISSUE TITLE
Aside opens when resizing window

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#130]
When you resize the page from full-width to say 50% width there's a good chance the aside will open by itself. Is there any logic I've missed? Otherwise I'd make sure it doesn't open unless you click the button.

**Comment by hugurp** [comment]
I think it is good like it is now.

The reason why it is open is:

- on large screens, when the aside is visible, if you resize to a smaller width:
  - if the aside was visible, it will stay visible (open). There you can click on the overlay to toggle it off.
  - if the aside was hidden, it will stay hidden (closed). You can click the toggle menu button to toggle it on.
- same logic applies to small screens, when expending the width.

What you want to fix is a corner of an edge case, an exception, that will insert complexity in the code for a very small outcome.

I think this issue is not one and should therefore be close.

**Comment by oskarrough** [comment]
You're right. Thanks!
