### ISSUE TITLE
Communication channels: user & user, users & team, team & team

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#136]
We have to take care not to be on too many channels as it will be impossible to manage everything. But the idea is not to become "moderators" in all these places, but help conversation and exchange grow.
Some communications channels can be specifically used and read by the team, and some other only promoted/created and be more informal.

A communication channel can also be used by users of radio4000 to help each other in solving issues.

# Questions:
- should/how can users communicate with the team, their feedback, ideas, issues.
- should/how can users communicate together / on one to one basis

# Actual channels of communication

## users & team

The idea is to communicate feedback, ideas, exchange point of views to make the overall experience as good as possible, for each of us.

- https://radio4000.com/feedback (one way only, except if they add email for answer)
- https://facebook.com/radio4000 (locked in facebook, not representative of user base, not something we want to "ask users to like")
- https://github.com/internet4000/radio4000/issues (and other r4 related repos, very technical related)

## users & users

This is a **huge** feature and we have made a point not to implement anything before we are sure what would be a great communication experience. There is no rush in implementing anything as Radio4000 is not developed to be an other social network, but a music management tool and discovery service.

The idea, though, is that some users would sometimes let other user know how great their channel are, maybe meet IRL, or just start a verbal or written exchange. Also many users are asking "hey do you know who is X, this radio is fantastic" etc.

At the moment users cannot communicate together on Radio4000 (except non-verbally, following each other). Their actual possibilities are:
- add a communication medium in their `channel.body`, or a `channel.link`, so both external to R4
- ear to mouth, old fashion way of letting someone know you are the owner of a specific channel
- "mentioning" an other channel in one's `track.body` or `channel.body` (even if more rare). This does not notify anyone, the the only time and place it will be seen is when a user goes by random to a channel in which they have been mentioned.

## team & team

- http://gihub.com/internet4000 (various repos)
- internet4000.slack.com (closed, and one page only for r4)
- email for those who know each other

## team to users
- https://blog.radio4000.com
- https://twitter.com/radio4000

## Possible new communication channels

Chat:
- https://riot.im/app/#/room/#radio4000:matrix.org & https://riot.im/app/#/room/#internet4000:matrix.org
- https://discordapp.com/channels/311165041825021953
- https://gitter.im

About these application vs slack:
- really designed to be open not only to teams
- riot is open source, does not require user communication, can be encrypted, can be built has a bridge between other communication medium (sms, irc, slack, email etc.)
- riot and discord have audio (if teams need)
- gitter is designed for developer chat (github connection).
So all these except Gitter are good for team & user communication

Forum:
- https://groups.google.com/forum/#!forum/radio4000
Free and already in used as it was our first medium of team/user communication
- https://www.discourse.org
Requires a server ($$$), and require users to register

**Comment by hellerve** [comment]
Voting against riot after using it. Really not my cup of tea.

**Comment by hugurp** [comment]
Do you have a suggestion for a more suitable option?

**Comment by hellerve** [comment]
I’m still of the opinion that Slack is the best option for regular users, and Gitter/Github for devs.

**Comment by hugurp** [comment]
I agree for Github. Their organisation system and project tied to code repositories work very well for collaboration.

Slack is very user friendly, Discord is also but centered arround gaming when Slack is more institutional. Though, both of them are closed is their memberships and need invitation, therefore the setup of a self invitation system. Also they are both vague about encryption and not free software.

I understand that you had an experience non-up to your standards using Riot, and I would like to clarify why I believe other systems such as Riot offer interesting alternatives.

- based on https://matrix.org ; Riot is only a web + mobile client to matrix.org
- can host your own matrix server and I would like to try that at some point on our servers
- can enable encryption on private or public channels
- uses https://www.signal.org/docs/ Double Ratchet for encryption
- feels and aims to be more like IRC, open or private channels. Decentralized networks with usernames registered on servers + : 
- web + mobile interfaces are by Riot, terminal implementations are by other developers using matrix
- cross systems: it can be used with bridges between different platforms
- does not require phone usage, and their mobile apps prompt you about using your local contacts or not
- people with interesting ideas and actions use it https://puri.sm/shop/librem-5/
- can be an alternative protocol for encrypted communication accross devices. Something to replace phone messaging apps and web based clients (matrix even has sms bridges).

I am not an expert in any of these fields, but the advantages over proprietary solutions appear multiple.

Disadvantages exist and I'd gladly discuss them, and I might be wrong about advising to use Matrix+Riot. If they are mostly UI, I am pretty certain il will improve will time (and maybe we can even contribute, or use an other implementation of the client). If these are from other matters and the teams behind the project don't plan to fix the issues it will make absolute sense not to use these projects.

**Comment by oskarrough** [comment]
Slack is, by far, the easiest option to use. It's great for new users. But it is closed source. In the spirit of Radio4000 I believe we should support open source alternatives when they exist. And here Matrix sounds like the best option available, for all the reasons listed above.

The Riot chat client for Matri has some pretty harsh UX flaws. It'll make it more difficult to get people to use it. I personally resisted using it for two months… Ended up making user-styles to make it bearable to look it. But this will improve because open source.

Also, the fact that we can bridge several protocols is really nice. The same chat can be accessed through IRC.  Use whatever client you prefer. Pros and cons. We could also set up the Slack bridge, why not? Then people can use whatever they prefer and we can keep the Matrix room as the official channel.

Riot client:  https://riot.im/app/#/room/#radio4000:matrix.org
IRCCloud client: https://www.irccloud.com/irc/freenode/channel/radio4000
Oldschool IRC client: https://webchat.freenode.net/?channels=radio4000

**Comment by oskarrough** [comment]
We've not set up bridges between Matrix, IRC and Slack. This means messages from these three sources will be synced. Users will not. It is pretty great and I feel we can now move forward… How about this:

We should advocate the URL

- https://riot.im/app/#/room/#radio4000:matrix.org.

But also mention that you're free to use any Matrix client as well as regular IRC via #radio4000 on the Freenode server.

- https://matrix.to/#/#radio4000:matrix.org
- https://webchat.freenode.net/?channels=radio4000
- https://www.irccloud.com/irc/freenode/channel/radio4000

Since joining Slack requires an invite, I don't see any reason to mention it.

**Comment by hugurp** [comment]
Perfect, let's do as you describe.
Let's keep our endpoints and docs simple.

**Comment by hugurp** [comment]
Radio4000 channel is now here — https://riot.im/app/#/room/#radio4000:matrix.org
