### ISSUE TITLE
Validate YouTube URL when adding a track

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#16]
We do have some sort of validation but it's not strong enough. You can add tracks with wrong urls and it won't complain about it. It should complain!

**Comment by hugurp** [comment]
Not sure it should complain.
We nmight have more than youtube later + is it really necessary to check the validity of a URL or is it the user that should check if his link is working?
I think the user should have some responsability in this action, and it would prevent the app to get more non-critical code

**Comment by oskarrough** [comment]
Also think we should draw the line somewhere but right now we have invalid tracks being added and probably more old invalid ones lying around. Could just because of typos from users or copy/paste errors etc.

For instance `httpss://www.youtube.com/watch?v=aC8i3Uwestw` is considered valid but our player won't play it and gives no warning.

So we either accept that or improve the validation?

**Comment by n1ru4l** [comment]
What about a video that gets deleted?

**Comment by hugurp** [comment]
When adding a track the URL you insert should be valid, otherwise the title won't be fetched. I assume users would only insert a URL that they know works.

Maybe we should give a UI warning that the track you inserted the URL of is invalid or not available?

Otherwise, in the player while in playing session, an invalid/not-available track will be skipped without warning.

Later, it would be nice to inform the track owner that the video is no longer available.

**Comment by hugurp** [comment]
Update:
I think **this issue can be closed,** because:

- if a track is added with a wrong URL (that validated), it will just not play it, and move to the next track with a valid URL
- when we have #113 this track will be shown as invalid and the user owner will have the oportunity to fix the track URL. If that user does not, it is their problem.
- making a regex, and an API call that checks for the track validity is imo overkill and will not bring anything to the UX
