### ISSUE TITLE
channel/edit writting in input trigger shortcuts

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#174]
why tho?

**Comment by oskarrough** [comment]
Because the only thing preventing it from triggering in inputs is some code from ember-keyboard that extends `{{input}}` and `{{textarea}}`. Found it on http://patience-tema-baron.github.io/ember-keyboard/#/usage

Fixed in https://github.com/internet4000/radio4000/commit/9a68e75c00615681a9e48d49457b668db884b3c0
