### ISSUE TITLE
Add `x` as shortcut to play current radio on the page

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#213]
Ref: https://github.com/internet4000/radio4000/issues/257

This feature would just play the first track, the same way going to the url `r4.com/$channel/play` plays `$channel`.

On which route should this feature be available?

- `/$channel/*` : play the current $channel
- `/all-the-rest` : should there be any action or this `x` shortcut does not trigger?

**Comment by oskarrough** [comment]
I like it. Sounds good to me to enable the shortcut on `channel` and all children routes, as you said.

What do you think about `p` instead? Or `shift+p`? To avoid introducing a second key for playing. In the case of `p` it would only work if you're not already playing.

**Comment by oskarrough** [comment]
ah yes, agree.

I'm just wondering if it's better to keep it to the `p` key, which we already using to play. Since this is sort of a contextual play it could be `shift-`p. Or do you think it's clearer with a new key, like `x`? I'm good either way.

- `p` plays
- `r` plays random
- `x` plays the page you're on (or `shift-p` or ?)

**Comment by hugurp** [comment]
Fixed, we're currently using `P`
