### ISSUE TITLE
Set up proper linting

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000#39]
We have some annoying linting rules for JavaScript at the moment. I'd like to clean them out and agree on something that is easier to work with and doesn't require contributors to understand some custom R4 rules and end up having to lint lint lint...

We could even have a `precommit` hook that runs `prettier` on everything. That would be a lot simpler.

**Comment by oskarrough** [comment]
For instance, which of these should be considered valid? Or should all of them?

```js
const {get} = Ember;
const { get } = Ember;
const {get} = Ember
const { get } = Ember
```

**Comment by hugurp** [comment]
code styling.
I follow no rules.
I don't know, don't really care but want it to work.

I want it easy to read an to maintain, i don't care about semi collons but don't care about removing them because they don't annoy me.

if you want to run prettier, just do.
Having to lint all the time to rules I don't know why I should agree, and which are different from project to project is annoying anyways.

Does the style has to be uniform, or could we just agree on some basic rules.
I think we have rules already, but do they need to be written down.

Those questions are as much boring as they are necessary, and as you see I don't have an answer.

**Comment by oskarrough** [comment]
> Those questions are as much boring as they are necessary, and as you see I don't have an answer

Where can I buy a t-shirt with this? 😍

**Comment by oskarrough** [comment]
Closing as we've updated the eslint rules in master to be more relaxed.
