### ISSUE TITLE
edit track scrolls page up, it should not

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#55]
When clicking on the edit track button, it opens the overlay to edit a track, and also scrolls the page up.
This is very annoying when doing many edits.

Also, should the edit track be a route instead of just a component?

**Comment by oskarrough** [comment]
Yes that's very annoying. It could be a "routable modal/overlay"? But that includes upgrading our `ember-modal-dialog`. I remember trying it a few times and stopping because of something. Might be time to try again. Also if we are very lucky it'll fix the scroll-issue or perhaps there is an option to disable it, if the addon is causing it.

**Comment by oskarrough** [comment]
if you edit a track from the new "latest tracks" on `channel.index` you are transitioned to `channel.track` which isn't optimal, especially with +1k tracks to load.
