### ISSUE TITLE
fix loading indicator on /all after moving from /root

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000#58]
When you load r4 from `/` or an other page which is not loading all radios, but still is loading at least one, moving to `/all` will display the already loaded radio, but of course not those who haven't yet been loaded.

The loading of the missing radios occurs as it should, but is not displayed in the UI.

Loading directly `/all` shows the loading indicator just fine.

**Comment by oskarrough** [comment]
In the `channels/all` route we do `model: return peekAll` and then `afterModel: findAll`.

Because the second step isn't returning a promise it renders immediately after the `peekAll`. This causes the "two-step" loading that we see. 

We could either remove that and do `model: return findAll`. Then the loading would appear in one step but the first load would also be slower. Perhaps it's better anyway?

**Comment by oskarrough** [comment]
The trick I mention above doesn't help this issue. Instead, this forces the model to always refresh. I'm not sure it's the right thing to do though. Will it load all channels again and again and again?

`store.findAll('channel', { reload: true })`

**Comment by oskarrough** [comment]
Seems fine in tracks-search branch (which is about to be merged). Closing.
